# This workflow will build a Java project with Maven
name: Continuous Integration

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v21.07.08
  workflow_dispatch: # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven Tycho
      run: mvn -B -U clean package
    - name: Upload linux artifact
      uses: actions/upload-artifact@v2
      with:
        name: org.palladiosimulator.somox.analyzer.rules.product-linux.gtk.x86_64.zip
        path: products/org.palladiosimulator.somox.analyzer.rules.product/target/products/org.palladiosimulator.somox.analyzer.rules.product-linux.gtk.x86_64.zip
    - name: Upload macosx artifact
      uses: actions/upload-artifact@v2
      with:
        name: org.palladiosimulator.somox.analyzer.rules.product-macosx.cocoa.x86_64.zip
        path: products/org.palladiosimulator.somox.analyzer.rules.product/target/products/org.palladiosimulator.somox.analyzer.rules.product-macosx.cocoa.x86_64.zip
    - name: Upload win32 artifact
      uses: actions/upload-artifact@v2
      with:
        name: org.palladiosimulator.somox.analyzer.rules.product-win32.win32.x86_64.zip
        path: products/org.palladiosimulator.somox.analyzer.rules.product/target/products/org.palladiosimulator.somox.analyzer.rules.product-win32.win32.x86_64.zip
