# This workflow will verify a Java project with Maven
name: Verify with Maven Tycho

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '4 2 * * 0' # once a week, Sundays at 02:04 UTC.
  workflow_dispatch: # manual trigger

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Maven Clean Verify
      run: mvn -B -U clean verify
